UT-Georeferencing-Tin-12d-4
bSI-InfraRoom/IFC-infra-unit-test pull request #21
Opened 2021-02-12 05:09 UTC by LeeGregory12d

## Unit test

tin with two colours

## Covered topics

*tick one/many*

- [x] project setup
- [x] georeferencing
- [ ] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [x] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

2021-02-12 08:12 UTC, pjanck approved these changes
LFTM

2021-03-18 19:44 UTC, pjanck commented
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

2021-04-06 11:56 UTC, AlexBrad1eyCT requested changes
unneeded IfcFacility per other Tin Examples

2021-04-06 11:56 UTC, AlexBrad1eyCT commented on Georeferencing-Tin-12d-4/Georeferencing-Tin-12d-4.ifc
> +#25 = IFCFACILITY('3cqrwCZ49CyfH7I3i_tMGd', #2, 'tin tiny', 'Description of tin tiny', $, #15, $, $, .ELEMENT.);
Same as other tins ne need for IfcFacility stratum can be contained under IfcSite

2021-06-07 09:37 UTC, AlexBrad1eyCT approved these changes
LFTM

2021-06-08 06:11 UTC, merged