UT-Alignment-12d-5
bSI-InfraRoom/IFC-infra-unit-test pull request #24
Opened 2021-02-12 06:53 UTC by LeeGregory12d

## Unit test

alignment with left and right arcs and left and right leading and trailing clothoid transitions in horizontal and no vertical

Axis is fudged because there is no IFC alignment geometry

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [x] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [ ] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

2021-02-12 08:18 UTC, pjanck requested changes
Small readme improvements.

2021-02-12 08:18 UTC, pjanck commented on UT-Alignment-12d-5/readme.md
> + and no vertical
```suggestion
 and no vertical alignment.
```

2021-02-12 08:18 UTC, pjanck commented on UT-Alignment-12d-5/readme.md
> +- straight of length 54.426
Sometimes there's a comma at the end, sometimes there isn't - I can't quite figure out the pattern.

Also: perhaps a table would have been a better choice here?

2021-02-15 08:07 UTC, pjanck approved these changes
LFTM

2021-03-18 19:45 UTC, pjanck commented
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

2021-03-22 06:03 UTC, jmirtsch approved these changes

2021-03-30 06:26 UTC, merged