UT-Alignment-12d-6
bSI-InfraRoom/IFC-infra-unit-test pull request #25
Opened 2021-02-12 07:37 UTC by LeeGregory12d

## Unit test

alignment with left arc in horizontal and crest and sag arcs for vertical
Axis is fudged because there is no IFC vertical geometry

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [x] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [ ] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

2021-02-12 08:20 UTC, pjanck requested changes
Sentences usually end with punctuation. :)

2021-02-12 08:20 UTC, pjanck commented on UT-Alignment-12d-6/readme.md
> +This scenario has an alignment with left arc in horizontal and crest and sag arcs for vertical
```suggestion
This scenario has an alignment with left arc in horizontal and crest and sag arcs for vertical.
```

2021-03-18 19:45 UTC, pjanck commented
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

2021-03-24 11:57 UTC, LeeGregory12d commented on UT-Alignment-12d-6/readme.md
> +This scenario has an alignment with left arc in horizontal and crest and sag arcs for vertical
This has been fixed in RC3 version

2021-03-24 12:03 UTC, LeeGregory12d commented
Stefan,
Was there anything else I had to change in the readme.md?

2021-06-08 06:19 UTC, pjanck approved these changes
Seen in the @jonm GeometryGym, seems fine.

2021-06-08 06:20 UTC, merged