Last alignment changes pending (Meeting Feb 10th)
bSI-InfraRoom/IFC-infra-unit-test pull request #28
Opened 2021-02-12 08:28 UTC by javierNadal

## Alignment1

*This scenario is a very simple alignment (horizontal + vertical).*

## Covered topics

*tick one/many*

- [ ] project setup
- [ ] georeferencing
- [ ] alignment semantics
- [*] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [ ] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

2021-02-12 10:01 UTC, pjanck requested changes
Please observe the markdown syntax and requirements for file naming.

2021-02-12 10:01 UTC, pjanck commented on Align_1/UT_Align_1.IFC
> +*/
Please use "-" instead of "_" in files' and folders' names.

2021-02-12 10:01 UTC, pjanck commented on Align_1/readme.md
> +## *Align_1*
No need for a title - please delete this line.
```suggestion

```

2021-02-12 10:01 UTC, pjanck commented on Align_1/readme.md
> +*This scenario is a very simple alignment (horizontal + vertical).*
```suggestion
This scenario is a very simple alignment (horizontal + vertical).
```

Please use normal font. The italics is used in the template to denote the content you need to input/change.

2021-02-12 10:01 UTC, pjanck commented on Align_1/readme.md
> +No prerequisites
I believe that ProjectSetup_1 would be a good base test.

2021-02-12 10:01 UTC, pjanck commented on Align_1/readme.md
> +| *UT_Align_1.xml*             | *same content of Ifc file, in LandXML format* |
Please use Grave Accent symbol for code snippets (like file names, or IFC entities. Also, no need for italics.

2021-02-12 10:08 UTC, pjanck commented
Please also merge in the new changes from the `main` branch so that IFC checking procedure runs your files as well.

2021-03-18 19:45 UTC, pjanck commented
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

2021-04-07 10:03 UTC, javierNadal commented
I don't know how remove IFC4x3_RC2 and add IFC4x3_RC3 labels...

2021-04-07 10:19 UTC, AlexBrad1eyCT commented
Done it for you but for reference!

![image](https://user-images.githubusercontent.com/74732183/113850985-ebadfe00-9792-11eb-8d57-3337ff192a3d.png)

2021-04-27 09:17 UTC, merged